# Challenge 2

In this challenge we will continue working with the `Pokemon` dataset. We will attempt solving a slightly more complex problem in which we will practice the iterative data analysis process you leaned in [this video](https://www.youtube.com/watch?v=xOomNicqbkk).

The problem statement is as follows:

**You are at a Pokemon black market planning to buy a Pokemon for battle. All Pokemon are sold at the same price and you can only afford to buy one. You cannot choose which specific Pokemon to buy. However, you can specify the type of the Pokemon - one type that exists in either `Type 1` or `Type 2`. Which type should you choose in order to maximize your chance of receiving a good Pokemon?**

To remind you about the 3 steps of iterative data analysis, they are:

1. Setting Expectations
1. Collecting Information
1. Reacting to Data / Revising Expectations

Following the iterative process, we'll guide you in completing the challenge.


## Problem Solving Iteration 1

In this iteration we'll analyze the problem and identify the breakthrough. The original question statement is kind of vague because we don't know what a *good pokemon* really means as represented in the data. We'll start by understanding the dataset and see if we can find some insights.

In [1]:
# Import libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
pokemon = pd.read_csv('Pokemon.csv')
pokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

From the data it seems whether a pokemon is good depends on its abilities as represented in the fields of `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total`. We are not sure about `Generation` and `Legendary` because they are not necessarily the decisive factors of the pokemon abilities.

But `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, `Speed`, and `Total` are a lot of fields! If we look at them all at once it's very complicated. This isn't Mission Impossible but it's ideal that we tackle this kind of problem after we learn Machine Learning (which you will do in Module 3). For now, is there a way to consolidate the fields we need to look into?

Fortunately there seems to be a way. It appears the `Total` field is computed based on the other 6 fields. But we need to prove our theory. If we can approve there is a formula to compute `Total` based on the other 6 abilities, we only need to look into `Total`.

We have the following expectation now:

#### The `Total` field is computed based on `HP`, `Attack`, `Defense`, `Sp. Atk`, `Sp. Def`, and `Speed`.

We need to collect the following information:

* **What is the formula to compute `Total`?**
* **Does the formula work for all pokemon?**

In the cell below, make a hypothesis on how `Total` is computed and test your hypothesis.

In [3]:
#my hypothesis is that all values in the featured columns equal to total. Shown in the cell below, we can see whether the rows are indeed true
cols_to_sum = ['HP', 'Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed']
pokemon['Total1'] = pokemon[cols_to_sum].sum(axis = 1)
pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total1  
0       65       65     45           1      False     318  
1       80       80     60           1      False     405  
2      100      100     80           1      False     525  
3      122      120     80           1      False     625  
4       60       50     65           1      False     309

In [4]:
pokemon['Total1'].value_counts() #all rows are true
pokemon['Total1']

0      318
1      405
2      525
3      625
4      309
      ... 
795    600
796    700
797    600
798    680
799    600
Name: Total1, Length: 800, dtype: int64

In [5]:
def True_or_False(x):
    if x['Total1'] == x['Total']:
        return True
    return False
pokemon['True_or_False'] = pokemon.apply(True_or_False, axis=1)
pokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  Total1  True_or_False  
0         65       65     45           1      False     318           True  
1         80       80     60           1      False     405           True  
2        100      100     80           1      False     525           True  
3        122      120     80           1      False     625           True  
4         60       50     65           1      False     309           True  
..       ...      ...    ...         ...        ...     ...            ...  
795      100      150     50           6       True     600           True  
796      160      110    110           6       True     700           True  
797      150      130     70           6       True     600           True  
798      170      130     80           6       True     680           True  
799      130       90     70           6       True     600           True  

[800 rows x 15 columns]

## Problem Solving Iteration 2

Now that we have consolidated the abilities fields, we can update the problem statement. The new problem statement is:

### Which pokemon type is most likely to have the highest `Total` value?

In the updated problem statement, we assume there is a certain relationship between the `Total` and the pokemon type. But we have two *type* fields (`Type 1` and `Type 2`) that have string values. In data analysis, string fields have to be transformed to numerical format in order to be analyzed. 

In addition, keep in mind that `Type 1` always has a value but `Type 2` is sometimes empty (having the `NaN` value). Also, the pokemon type we choose may be either in `Type 1` or `Type 2`.

Now our expectation is:

#### `Type 1` and `Type 2` string variables need to be converted to numerical variables in order to identify the relationship between `Total` and the pokemon type.

The information we need to collect is:

#### How to convert two string variables to numerical?

Let's address the first question first. You can use a method called **One Hot Encoding** which is frequently used in machine learning to encode categorical string variables to numerical. The idea is to gather all the possible string values in a categorical field and create a numerical field for each unique string value. Each of those numerical fields uses `1` and `0` to indicate whether the data record has the corresponding categorical value. A detailed explanation of One Hot Encoding can be found in [this article](https://hackernoon.com/what-is-one-hot-encoding-why-and-when-do-you-have-to-use-it-e3c6186d008f). You will formally learn it in Module 3.

For instance, if a pokemon has `Type 1` as `Poison` and `Type 2` as `Fire`, then its `Poison` and `Fire` fields are `1` whereas all other fields are `0`. If a pokemon has `Type 1` as `Water` and `Type 2` as `NaN`, then its `Water` field is `1` whereas all other fields are `0`.

#### In the next cell, use One Hot Encoding to encode `Type 1` and `Type 2`. Use the pokemon type values as the names of the numerical fields you create.

The new numerical variables you create should look like below:

![One Hot Encoding](../images/one-hot-encoding.png)

In [6]:
#Looking at the new data types
pokemon.dtypes

#                 int64
Name             object
Type 1           object
Type 2           object
Total             int64
HP                int64
Attack            int64
Defense           int64
Sp. Atk           int64
Sp. Def           int64
Speed             int64
Generation        int64
Legendary          bool
Total1            int64
True_or_False      bool
dtype: object

In [7]:
#Only looking to compare 3 columns because total is the summation of all the numbers, therefore considering Type1 and Type2 colum
x1 = pokemon[['Type 1']]
x1

Type 1
0      Grass
1      Grass
2      Grass
3      Grass
4       Fire
..       ...
795     Rock
796     Rock
797  Psychic
798  Psychic
799     Fire

[800 rows x 1 columns]

In [8]:
# Handling unknown variables
encoder = OneHotEncoder(handle_unknown = 'ignore').fit(x1)

# #2. Show the new categories
print(encoder.categories_)

# # 3. Change the variable into an array
encoded_type1 = encoder.transform(x1).toarray()
print(encoded_type1)

# # 4. Let's see if it worked
onehot_encoded_type1 = pd.DataFrame(encoded_type1, columns=['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'])
onehot_encoded_type1.head()

[array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

   Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
1     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
2     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
3     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
4     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0

In [16]:
x2=pokemon[['Type 2']]
x2.value_counts(dropna=False)
x2 = x2.dropna()
x2.head()

Type 2
0  Poison
1  Poison
2  Poison
3  Poison
6  Flying

In [17]:
#We need to train the encoder with a command to create dummy variables
encoder = OneHotEncoder(handle_unknown = 'ignore').fit(x2) # should use the same encoder for the OneHot Encoding

#2. Show the new categories
print(encoder.categories_)

# 3. Change the variable into an array
encoded_type2 = encoder.transform(x2).toarray()
print(encoded_type2)

# 4. Let's see if it worked
onehot_encoded_type2 = pd.DataFrame(encoded_type2, columns=['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'])
#onehot_encoded_type2 = onehot_encoded_type2.drop([' '], axis = 1)
onehot_encoded_type2.head()

[array(['Bug', 'Dark', 'Dragon', 'Electric', 'Fairy', 'Fighting', 'Fire',
       'Flying', 'Ghost', 'Grass', 'Ground', 'Ice', 'Normal', 'Poison',
       'Psychic', 'Rock', 'Steel', 'Water'], dtype=object)]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
1  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
2  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
3  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
4  0.0   0.0     0.0       0.0    0.0       0.0   0.0     1.0    0.0    0.0   

   Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0     0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1     0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2     0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3     0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0

In [18]:
types_encoded = pd.concat([onehot_encoded_type1, onehot_encoded_type2]).groupby(level=0).max()
types_encoded

Bug  Dark  Dragon  Electric  Fairy  Fighting  Fire  Flying  Ghost  Grass  \
0    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
1    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
2    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
3    0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    1.0   
4    0.0   0.0     0.0       0.0    0.0       0.0   1.0     1.0    0.0    0.0   
..   ...   ...     ...       ...    ...       ...   ...     ...    ...    ...   
795  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
796  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
797  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
798  0.0   0.0     0.0       0.0    0.0       0.0   0.0     0.0    0.0    0.0   
799  0.0   0.0     0.0       0.0    0.0       0.0   1.0     0.0    0.0    0.0   

     Ground  Ice  Normal  Poison  Psychic  Rock  Steel  Water  
0       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
1       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
2       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
3       0.0  0.0     0.0     1.0      0.0   0.0    0.0    0.0  
4       0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  
..      ...  ...     ...     ...      ...   ...    ...    ...  
795     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
796     0.0  0.0     0.0     0.0      0.0   1.0    0.0    0.0  
797     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
798     0.0  0.0     0.0     0.0      1.0   0.0    0.0    0.0  
799     0.0  0.0     0.0     0.0      0.0   0.0    0.0    0.0  

[800 rows x 18 columns]

## Problem Solving Iteration 3

Now we have encoded the pokemon types, we will identify the relationship between `Total` and the encoded fields. Our expectation is:

#### There are relationships between `Total` and the encoded pokemon type variables and we need to identify the correlations.

The information we need to collect is:

#### How to identify the relationship between `Total` and the encoded pokemon type fields?

There are multiple ways to answer this question. The easiest way is to use correlation. In the cell below, calculate the correlation of `Total` to each of the encoded fields. Rank the correlations and identify the #1 pokemon type that is most likely to have the highest `Total`.

In [19]:
Total = pokemon[['Total']]
Total

Total
0      318
1      405
2      525
3      625
4      309
..     ...
795    600
796    700
797    600
798    680
799    600

[800 rows x 1 columns]

In [20]:
corr_check = pd.concat([types_encoded,Total], axis=1)

In [24]:
corr_total = types_encoded.corrwith(pokemon['Total'], axis=0)
display(corr_total)
display(corr_total.max())

Bug        -0.138677
Dark       -0.014648
Dragon      0.138575
Electric    0.013347
Fairy       0.002866
Fighting   -0.044286
Fire        0.056228
Flying     -0.035830
Ghost       0.040590
Grass      -0.052584
Ground     -0.029579
Ice        -0.025357
Normal     -0.109082
Poison     -0.064853
Psychic     0.030923
Rock        0.016584
Steel       0.068492
Water      -0.009789
dtype: float64

0.13857507771964764

In [26]:
corr_total.sort_values(ascending = False).head(3)

Dragon    0.138575
Steel     0.068492
Fire      0.056228
dtype: float64

# Bonus Question

Say now you can choose both `Type 1` and `Type 2` of the pokemon. In order to receive the best pokemon, which types will you choose?

In [29]:
display(corr_total.sort_values(ascending=False).head(3))

Dragon    0.138575
Steel     0.068492
Fire      0.056228
dtype: float64